name: 'Docker Publish'

on:
  push:
    tags:
      - 'v*.*.*'
  schedule:
    - cron: '0 0 10,20,30 * *'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  publish-stable:
    name: Docker Publish

    runs-on: ubuntu-latest

    if: ${{ github.event_name != 'schedule' && !contains(github.ref, '-') }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Prepare
        run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: '.'
          file: './Dockerfile'
          platforms: 'linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7'
          push: true
          tags: |
            captnsisko/vaultwarden-backup:latest
            captnsisko/vaultwarden-backup:${{ env.TAG }}
